bindkey -e

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

#
# プラグインインストール
#
# Ninja
zinit ice wait'!0' src"ninja.zsh" silent; zinit light cm-hirano-shigetoshi/cli-ninja # old
zinit ice atclone"bash build.sh" atpull'%atclone' src"ninja.zsh" silent
zinit light cm-hirano-shigetoshi/CommandLineNinja

# ディレクトリスタック
zinit ice atclone"bash build.sh" atpull'%atclone' src"d.zsh"
zinit light cm-hirano-shigetoshi/d
bindkey "^d^d" d

# コマンド履歴
zinit ice wait'!0' src"command-history" silent; zinit light shogetoshi/command-history.zsh
bindkey "^r" _command_history_select
zinit ice atclone"bash build.sh" atpull'%atclone' src"history.zsh"
zinit light cm-hirano-shigetoshi/CommandHistory
bindkey "^t" fzf-command-history

# コマンドに色を付ける
zinit ice wait'!0' silent; zinit light zdharma/fast-syntax-highlighting
# クリップボード履歴
zinit ice wait'!0' silent; zinit light cm-hirano-shigetoshi/clipboard-history
# クリップボード変換テンプレ
zinit ice wait'!0' silent; zinit light cm-hirano-shigetoshi/clipboard-convert-template
# スニペットの貼り付け機能
zinit ice wait'!0' silent; zinit light cm-hirano-shigetoshi/snippet
# ファイル名検索
zinit ice wait'!0' src"fzf-fd" silent; zinit light shogetoshi/fzf-fd.zsh
bindkey '\e[Z' fzf-fd
# fzf-rg
zinit ice wait'!0' src"fzf-rg" silent; zinit light shogetoshi/fzf-rg.zsh
bindkey '^s' fzf-rg
# Powerlevel10k
zinit ice depth=1
zinit light romkatv/powerlevel10k

# git
zinit ice src"git-fzf.zsh" silent; zinit light cm-hirano-shigetoshi/git-fzf
bindkey "^g^s" git-status
bindkey "^g^l" git-log
bindkey "^g^b" git-branch

# aws cliコマンド拡張
zinit ice wait'!0' src"aws-cli-fzf.zsh" silent; zinit light cm-hirano-shigetoshi/aws-cli-fzf


#
# mise
#
[[ -e "$HOME/.local/bin/mise" ]] && eval "$($HOME/.local/bin/mise activate zsh)"
export PATH="$HOME/.local/share/mise/shims:$PATH"

#
# 一般の設定
#
# Ctrl+s（ターミナルロック）を無効化。これがないとCtrl+sを含むキーバインドが無効になる。
stty stop undef
# Ctrl+d でターミナルを閉じないようにする
setopt IGNOREEOF
# 特殊文字の中で「単語」の境界として扱う文字を指定
WORDCHARS="*?.-_[]~&;!#$%^(){}<>"
# ヒストリにはスペースなどを整形した状態で保存する
setopt hist_reduce_blanks
# 直前と同じヒストリは記録しない
setopt hist_ignore_dups
# deleteキー
bindkey "^[[3~"  delete-char
bindkey "^[3;5~" delete-char

#
# 補完の設定
#
# zsh の補完機能を使うおまじない
autoload -Uz compinit
compinit -C
# 補完候補にも色を付ける
zstyle ':completion:*' list-colors 'di=34;1'
# ファイル名の途中でも補完候補とし、小文字は大文字としても検索
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'l:|=* r:|[.-]=* m:{a-z}={A-Z}'

#
# 一時的な設定
#
export EDITOR="nvim"
if which arch >/dev/null 2>&1 && [[ $(arch) = "arm64" ]]; then
  alias arm64='arch -arch arm64'
  alias x86='arch -arch x86_64'
fi
alias which="$(where which | grep -v 'built-in' | head -1)"

#
# Java
#
if [[ -d /Library/Java/JavaVirtualMachines/amazon-corretto-15.jdk/Contents/Home ]]; then
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-15.jdk/Contents/Home
fi

# 意図的に使いたいものは最後に加える
PATH="$HOME/bin/main:$PATH"
# 実験中のファイルはbin/developに置く
PATH="$HOME/bin/develop:$PATH"

export BAT_THEME="Monokai Extended"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/hirano.shigetoshi/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ -d "$HOME/.config/zsh" ]]; then
    [[ ! -f "$HOME/.config/zsh/p10k.zsh" ]] || source "$HOME/.config/zsh/p10k.zsh"
else
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
fi

#
# エイリアス
#
alias ls='eza -Ah --time-style long-iso --git --icons -F=always'
alias sort='LC_ALL=C sort'
alias vim='nvim'
alias 'ka-sa-'='cursor-agent'
alias 1pass='set -a && source "$HOME/.local/share/env" && set +a &&'
alias ga='git add -u'
alias gaa='git add .'
alias gd='git diff'
alias gdn='git diff --name-status'
alias envf="env | fzf --reverse --wrap --preview 'echo {} | sed \"s/^[^=]\+=//\" | tr \":\" \"\n\"' --preview-window 'up:wrap'"

if [[ $CLAUDECODE = "1" ]]; then
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        alias rm='echo "AIによるこのコマンドの利用は禁止されています。代替コマンドの実行はせずユーザに指示を仰いでください。"'
    fi
fi

typeset -U path PATH

[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"

alias npx='echo "WARNING: npx は実行しないでください。npmの代わりにpnpmを使用してください。" && false'
alias npm='echo "WARNING: npm は実行しないでください。npmの代わりにpnpmを使用してください。" && false'

# pnpm
export PNPM_HOME="/Users/hirano.shigetoshi/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# ~/.zshrc に追加

fzf-ls-widget() {
  local selected
  selected=$(ls -lQ --color=always | grep -v '^total' | fzf --reverse --multi --ansi -d '"' --nth 2 | awk -F '"' '{print $2}' | sed 's/.*/"&"/' | paste -s -d ' ')
  if [[ -n "$selected" ]]; then
    LBUFFER+="$selected "
  fi
  zle redisplay
}

zle -N fzf-ls-widget
bindkey '^l^s' fzf-ls-widget  # Ctrl+O で起動


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/hirano.shigetoshi/.lmstudio/bin"
# End of LM Studio CLI section
