onboarding = false

[ui]
prompt_new_tab_name = false

[keys]
prefix = "ctrl+;"

new_tab = ["ctrl+command+;"]
previous_tab = ["ctrl+command+["]
next_tab = ["ctrl+command+]"]
close_tab = ["ctrl+command+shift+/"]

split_vertical = ["ctrl+command+."]
split_horizontal = ["ctrl+command+,"]

focus_pane_left = ["ctrl+command+h"]
focus_pane_down = ["ctrl+command+j"]
focus_pane_up = ["ctrl+command+k"]
focus_pane_right = ["ctrl+command+l"]
swap_pane_left = ["prefix+ctrl+h"]
swap_pane_down = ["prefix+ctrl+j"]
swap_pane_up = ["prefix+ctrl+k"]
swap_pane_right = ["prefix+ctrl+l"]
close_pane = ["ctrl+command+/"]
zoom = ["ctrl+command+shift+m"]

copy_mode = ["ctrl+command+shift+["]

